### ISSUE TITLE
Multi-line shell script triggers wrong highlighting on next command

### ISSUE THREAD

**Issue by raqua** [danielchatfield/atom-jinja2#14]
Please see attached screenshot.
![screenshot from 2016-04-04 13 02 51](https://cloud.githubusercontent.com/assets/1541886/14246204/d35509ae-fa65-11e5-8bbd-577c3e26dddc.png)

Highlighting on line 29 is incorrect due to previous usage of "|" followed by commands (line 24-26).
This is Saltstack Jinja and it is otherwise valid code.

**Comment by danielchatfield** [comment]
@raqua I'm a little confused, is this a Jinja template?

The grammar only provides syntax highlighting for the jinja part - it doesn't know about the rest.

**Comment by raqua** [comment]
Sorry, my bad, this is actually YAML, not Jinja. Those are used both in Salt and I got that mixed.
