### ISSUE TITLE
HTML syntax highlighting not working on .j2 files.

### ISSUE THREAD

**Issue by Azleur** [danielchatfield/atom-jinja2#19]
When I first installed the Atom module I changed all my template files from .html to .j2 so that the package would work. Now after updating I find that only Jinja specific commands are highlighted, while the bulk of the html code gets no highlighting.

**Comment by zlliang** [comment]
You can try to change the files from `.j2` to `.html.j2`.

**Comment by Aelexe** [comment]
Alternatively you can remove the j2 and/or jinja2 extension from conf (jinja templates).cson as a temporary fix to save you changing your file extensions.

**Comment by sapalamut** [comment]
thanx dude!
