### ISSUE TITLE
syntax highlighting for YAML (Jinja Templates) broken

### ISSUE THREAD

**Issue by abueschel** [danielchatfield/atom-jinja2#22]
Since some of the less recent Atom and/or package updates, syntax highlighting for Jinja2 elements seems to be broken.

I allready filed a nearly identical issue here https://github.com/JonGretar/language-salt/issues/8, but could confirm the issue is wthin `atom-jinja2` (using  "YAML (Jinja Templates)" directly.

Atom 1.14.2 on macOS 10.12.3 (16D32)
language-yaml 0.28.0
atom-jinja2 0.6.0

What it looks like:

![bb9dd11c-b007-11e6-8433-418193896b7b](https://cloud.githubusercontent.com/assets/13065401/23029474/f4365eb6-f46a-11e6-9f83-46c896a2186e.png)

What Jinja2 should look like (works in only in some situations):

![e969dabe-b007-11e6-8bca-ba51967ab715](https://cloud.githubusercontent.com/assets/13065401/23029472/f1e436f6-f46a-11e6-84c4-76fcfe10a038.png)

Original code example ([SaltStack](https://saltstack.com/) SLS file):

```salt
# pkg.latest
# service.running

httpd:
  pkg:
    - installed
    {% if grains['os'] == 'RedHat' or grains['os'] == 'Fedora' or grains['os'] == 'CentOS' %}
    - name: httpd
    {% elif grains['os'] == 'Debian' or grains['os'] == 'Ubuntu'%}
    - name: apache2
    {% elif grains['os'] == 'Gentoo' or grains['os'] == 'Arch' or grains['os'] == 'FreeBSD' %}
    - name: apache
    {% endif %}
  service:
    - running
    {% if grains['os'] == 'Debian' or grains['os'] == 'Ubuntu' or grains['os'] == 'Gentoo' %}
    - name: apache2
    {% endif %}
    - enable: True
    - require:
      - pkg: httpd

date > /tmp/started_apache:
  cmd:
    - wait
    - watch:
      - service: httpd

{#- Comment #}
```

**Comment by BlaineEXE** [comment]
I'm also seeing the same issue in SLS files. 

Update: It seems like Atom is still using basic YAML syntax highlighting on jinja lines. Could the plugin not be overriding the highlighting correctly for lines it finds that are matching?

**Not working**
![image](https://cloud.githubusercontent.com/assets/3989526/24167390/38d50ac8-0e3c-11e7-8423-73d1a178f925.png)

**Both working (before any YAML content in the file) and non-working (after YAML content in the file)**
![image](https://cloud.githubusercontent.com/assets/3989526/24167433/59f24aae-0e3c-11e7-9ee4-f2cab5945e3b.png)

**Comment by BlaineEXE** [comment]
An interesting note, if you add a colon (:) somewhere in the middle or end of the non-highlighting jinja lines, the highlighting will begin working again. I wonder if this is due to some issue in the YAML highlighting code.

Addendum: I don't think the below (YAML-only) syntax is correct.

![image](https://cloud.githubusercontent.com/assets/3989526/24226134/4b6ba270-0f2a-11e7-9e8f-943626cbfde2.png)

**Comment by BlaineEXE** [comment]
I suspect the issue may be fixed with this bug:

https://github.com/atom/language-yaml/issues/78

**Comment by BlaineEXE** [comment]
@spaceheadx , the issue is solved if you `apm install language-yaml`, though the change will eventually make it into the Atom master.

**Comment by abueschel** [comment]
@BlaineEXE, thanks a lot for digging into this. I can confirm that `apm install language-yaml` does fix the issue. I'll close the issue, because it's unrelated to `atom-jinja2`.
